spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/demo
    name: stalk
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

